//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"github.com/gaarutyunov/guix/pkg/runtime"
)

type BitcoinChart struct {
	Data     []OHLCV
	DataChan chan []OHLCV
}

func NewBitcoinChart(data []OHLCV, dataChan chan []OHLCV) runtime.Chart {
	return &BitcoinChart{Data: data, DataChan: dataChan}
}
func (s *BitcoinChart) RenderChart() *runtime.GPUNode {
	return runtime.ChartNode(runtime.ChartBackground(0.08, 0.09, 0.12, 1.0), runtime.XAxis(runtime.AxisPosition("bottom"), runtime.TimeScale(true), runtime.GridLines(true), runtime.Label("Time")), runtime.YAxis(runtime.AxisPosition("right"), runtime.GridLines(true), runtime.Label("Price (USD)")), runtime.CandlestickSeries(runtime.ChartData(s.Data), runtime.ChartDataChannel(s.DataChan), runtime.UpColor(0.18, 0.80, 0.44, 1.0), runtime.DownColor(0.91, 0.27, 0.38, 1.0), runtime.WickColor(0.6, 0.6, 0.65, 1.0), runtime.BarWidth(0.8)))
}
