linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/gaarutyunov/guix
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  staticcheck:
    checks: ["all"]

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - structcheck
    - varcheck
    - deadcode
    - typecheck

  disable:
    - golint  # Deprecated

issues:
  exclude-rules:
    # Exclude generated files
    - path: _gen\.go$
      linters:
        - gofmt
        - goimports
        - govet
        - errcheck
        - staticcheck

run:
  timeout: 5m
  build-tags:
    - js
    - wasm
