//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"fmt"
	"syscall/js"
)

var console = js.Global().Get("console")

func log(args ...interface{}) {
	// Convert all args to strings to avoid js.ValueOf errors
	jsArgs := make([]interface{}, len(args))
	for i, arg := range args {
		jsArgs[i] = fmt.Sprint(arg)
	}
	console.Call("log", jsArgs...)
}
