//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package shaders

import (
	_ "embed"
	"unsafe"
)

type ChartUniforms struct {
	ViewportSize [2]float32
	DataRange    [4]float32
	Padding      [4]float32
	CandleWidth  float32
	UpColor      [4]float32
	DownColor    [4]float32
	WickColor    [4]float32
}

func (s *ChartUniforms) ToBytes() []byte {
	return unsafe.Slice((*byte)(unsafe.Pointer(s)), int(unsafe.Sizeof(*s)))
}
func init() {
	expectedSize := uintptr(112)
	if unsafe.Sizeof(ChartUniforms{}) != expectedSize {
		panic("ChartUniforms size mismatch with WGSL")
	}
}

type Candle struct {
	Timestamp float32
	Open      float32
	High      float32
	Low       float32
	Close     float32
	Volume    float32
}

func (s *Candle) ToBytes() []byte {
	return unsafe.Slice((*byte)(unsafe.Pointer(s)), int(unsafe.Sizeof(*s)))
}
func init() {
	expectedSize := uintptr(24)
	if unsafe.Sizeof(Candle{}) != expectedSize {
		panic("Candle size mismatch with WGSL")
	}
}

//go:embed candlestick_types.wgsl
var CandlestickTypesShaderSource string
