//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package shaders

import (
	_ "embed"
	"unsafe"
)

type LineUniforms struct {
	ViewportSize [2]float32
	DataRange    [4]float32
	Padding      [4]float32
	StrokeWidth  float32
	StrokeColor  [4]float32
	FillEnabled  uint32
	FillColor    [4]float32
}

func (s *LineUniforms) ToBytes() []byte {
	return unsafe.Slice((*byte)(unsafe.Pointer(s)), int(unsafe.Sizeof(*s)))
}
func init() {
	expectedSize := uintptr(112)
	if unsafe.Sizeof(LineUniforms{}) != expectedSize {
		panic("LineUniforms size mismatch with WGSL")
	}
}

type Point struct {
	X float32
	Y float32
}

func (s *Point) ToBytes() []byte {
	return unsafe.Slice((*byte)(unsafe.Pointer(s)), int(unsafe.Sizeof(*s)))
}
func init() {
	expectedSize := uintptr(8)
	if unsafe.Sizeof(Point{}) != expectedSize {
		panic("Point size mismatch with WGSL")
	}
}

//go:embed line_types.wgsl
var LineTypesShaderSource string
