//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type App struct {
	app                *runtime.App
	stateChannel       chan CalculatorState
	calculatorInstance *Calculator
}

func NewApp() *App {
	c := &App{}
	c.stateChannel = make(chan CalculatorState, 10)
	c.stateChannel <- CalculatorState{Display: "0", PreviousValue: 0, Operator: "", WaitingForOperand: false}
	c.calculatorInstance = NewCalculator(WithStateChannel(c.stateChannel))
	return c
}
func (c *App) BindApp(app *runtime.App) {
	log("App: BindApp called")
	c.app = app
	if c.calculatorInstance != nil {
		c.calculatorInstance.BindApp(app)
	}
}
func (c *App) Render() *runtime.VNode {
	log("App: Render called")
	return func() *runtime.VNode {
		return runtime.Div(runtime.Class("app-container"), runtime.H1(runtime.Text("Calculator")), c.calculatorInstance.Render(), runtime.Div(runtime.Class("info"), runtime.Text("Built with Guix")))
	}()
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
