//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type App struct {
	app *runtime.App
}

func NewApp() *App {
	c := &App{}
	return c
}
func (c *App) BindApp(app *runtime.App) {
	c.app = app
}
func (c *App) Render() *runtime.VNode {
	return runtime.Div(runtime.ID("app"), runtime.Class("webgpu-container"), runtime.Canvas(runtime.ID("webgpu-canvas"), runtime.Width(600), runtime.Height(400), runtime.SceneProp(NewCubeScene(0, 0))), runtime.Div(runtime.Class("loading"), runtime.Text("Loading WebGPU...")))
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
