//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type App struct {
	app              *runtime.App
	rotationX        float64
	rotationY        float64
	autoRotate       bool
	speed            float64
	commands         chan ControlCommand
	controlState     chan ControlState
	controlsInstance *Controls
}

func NewApp() *App {
	c := &App{}
	c.rotationX = 0.0
	c.rotationY = 0.0
	c.autoRotate = true
	c.speed = 1.0
	c.commands = make(chan ControlCommand, 10)
	c.controlState = make(chan ControlState, 10)
	go func() {
		c.controlState <- ControlState{AutoRotate: c.autoRotate, Speed: float32(c.speed)}
	}()
	go func() {
		for cmd := range c.commands {
			switch cmd.Type {
			case "rotX":
				c.rotationX += float64(cmd.Value)
			case "rotY":
				c.rotationY += float64(cmd.Value)
			case "autoRotate":
				c.autoRotate = !c.autoRotate
			case "speed":
				c.speed = float64(cmd.Value)
			}
			select {
			case c.controlState <- ControlState{AutoRotate: c.autoRotate, Speed: float32(c.speed)}:
			default:
			}
		}
	}()
	c.controlsInstance = NewControls(WithCommands(c.commands), WithState(c.controlState))
	return c
}
func (c *App) BindApp(app *runtime.App) {
	c.app = app
	if c.controlsInstance != nil {
		c.controlsInstance.BindApp(app)
	}
}
func (c *App) Render() *runtime.VNode {
	return func() *runtime.VNode {
		return runtime.Div(runtime.Class("webgpu-container"), runtime.TabIndex(0), runtime.Canvas(runtime.ID("webgpu-canvas"), runtime.Width(600), runtime.Height(400), runtime.GPUScene(NewCubeScene(float32(c.rotationX), float32(c.rotationY)))), c.controlsInstance.Render())
	}()
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
