//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type App struct {
	app              *runtime.App
	commands         chan ControlCommand
	controlsInstance *Controls
}

func NewApp() *App {
	c := &App{}
	c.commands = make(chan ControlCommand, 10)
	c.controlsInstance = NewControls(WithCommands(c.commands))
	return c
}
func (c *App) BindApp(app *runtime.App) {
	c.app = app
	if c.controlsInstance != nil {
		c.controlsInstance.BindApp(app)
	}
}
func (c *App) Render() *runtime.VNode {
	return func() *runtime.VNode {
		return runtime.Div(runtime.Class("webgpu-container"), runtime.TabIndex(0), runtime.OnKeyDown(makeKeyboardHandler(c.commands)), runtime.Canvas(runtime.ID("webgpu-canvas"), runtime.Width(600), runtime.Height(400), runtime.GPUScene(NewCubeScene(0, 0))), c.controlsInstance.Render())
	}()
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
