package // Code generated by guix. DO NOT EDIT.
main

import (
	"fmt"
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type App struct {
	app *runtime.App
}

func NewApp() *App {
	c := &App{}
	return c
}
func (c *App) Render() *runtime.VNode {
	return func() *runtime.VNode {
		counter := make(chan int, 10)
		return runtime.Div(runtime.Class("app-container"), runtime.H1(runtime.Text("Counter Example")), runtime.Div(runtime.Class("input-group"), runtime.Input(runtime.Type("number"), runtime.Placeholder("Enter a number"), runtime.ID("counter-input"), runtime.OnInput(func(e Event) {
			value := e.Target.Value
			counter <- 42
		}))), runtime.Counter(runtime.WithCounterChannel(c.Counter)))
	}()
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
