// Code generated by guix. DO NOT EDIT.
package main

import (
	"strconv"
	"syscall/js"

	"github.com/gaarutyunov/guix/pkg/runtime"
)

type App struct {
	app          *runtime.App
	counter      chan int
	counterComp  *Counter
}

func NewApp() *App {
	app := &App{
		counter: make(chan int, 10),
	}
	app.counterComp = NewCounter(WithCounterChannel(app.counter))
	return app
}

func (a *App) BindApp(app *runtime.App) {
	a.app = app
	a.counterComp.BindApp(app)
}

func (a *App) Render() *runtime.VNode {
	return runtime.Div(
		runtime.Class("app-container"),
		runtime.H1(runtime.Text("Counter Example")),
		runtime.Div(
			runtime.Class("input-group"),
			runtime.Input(
				runtime.Type("number"),
				runtime.Placeholder("Enter a number"),
				runtime.ID("counter-input"),
				runtime.OnInput(func(e runtime.Event) {
					value := e.Target.Value
					if n, err := strconv.Atoi(value); err == nil {
						// Non-blocking send
						select {
						case a.counter <- n:
						default:
							// Channel full, skip
						}
					}
				}),
			),
		),
		a.counterComp.Render(),
	)
}

func (a *App) Mount(parent js.Value) {
	runtime.Mount(a.Render(), parent)
}

func (a *App) Unmount() {
	if a.counter != nil {
		close(a.counter)
	}
}

func (a *App) Update() {
	if a.app != nil {
		a.app.Update()
	}
}
