package // Code generated by guix. DO NOT EDIT.
main

import (
	"fmt"
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type CounterProps struct {
	Count int
}
type CounterOption func(*Counter)

func WithCount(v int) CounterOption {
	return func(c *Counter) {
		c.Count = v
	}
}

type Counter struct {
	app   *runtime.App
	Count int
}

func NewCounter(opts ...CounterOption) *Counter {
	c := &Counter{}
	for _, opt := range opts {
		opt(c)
	}
	return c
}
func (c *Counter) Render() *runtime.VNode {
	return runtime.Div(runtime.Class("counter-display"), runtime.Span(runtime.Class("counter-value"), runtime.Text("Counter: "+fmt.Sprint(c.Count))))
}
func (c *Counter) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *Counter) Unmount() {
}
func (c *Counter) Update() {
	if c.app != nil {
		c.app.Update()
	}
}

type App struct {
	app *runtime.App
}

func NewApp() *App {
	c := &App{}
	return c
}
func (c *App) Render() *runtime.VNode {
	return runtime.Div(runtime.Class("app-container"), runtime.H1(runtime.Text("Counter Example")), runtime.Div(runtime.Class("input-group"), runtime.Input(runtime.Type("number"), runtime.Placeholder("Enter a number"), runtime.Value("0"), runtime.ID("counter-input"))), runtime.Counter(runtime.WithCount(0)))
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
