// Package codegen provides Go code generation for GPU structs
package codegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"strings"

	guixast "github.com/gaarutyunov/guix/pkg/ast"
)

// GPUGoGenerator generates Go code from GPU struct declarations
type GPUGoGenerator struct {
	fset           *token.FileSet
	pkg            string
	shaderFilename string
}

// NewGPUGoGenerator creates a new GPU Go code generator
func NewGPUGoGenerator(pkg string, shaderFilename string) *GPUGoGenerator {
	return &GPUGoGenerator{
		fset:           token.NewFileSet(),
		pkg:            pkg,
		shaderFilename: shaderFilename,
	}
}

// Generate generates Go code for GPU structs
func (g *GPUGoGenerator) Generate(file *guixast.File) ([]byte, error) {
	var decls []ast.Decl

	// Generate imports
	decls = append(decls, g.generateImports())

	// Generate struct types
	for _, gpuStruct := range file.GPUStructs {
		structDecl := g.generateGPUStruct(gpuStruct)
		decls = append(decls, structDecl)

		// Generate helper methods
		helperDecls := g.generateHelperMethods(gpuStruct)
		decls = append(decls, helperDecls...)
	}

	// Generate shader source constant
	if len(file.GPUStructs) > 0 || len(file.GPUFunctions) > 0 {
		embedDecl := g.generateShaderEmbed()
		decls = append(decls, embedDecl...)
	}

	// Build Go AST file
	goFile := &ast.File{
		Name:  ast.NewIdent(file.Package),
		Decls: decls,
	}

	// Format and output
	var buf bytes.Buffer

	// Write build tags for WASM target
	buf.WriteString("//go:build js && wasm\n")
	buf.WriteString("// +build js,wasm\n\n")

	// Write header comment
	buf.WriteString("// Code generated by guix. DO NOT EDIT.\n\n")

	// Format the rest of the code
	if err := format.Node(&buf, g.fset, goFile); err != nil {
		return nil, fmt.Errorf("format error: %w", err)
	}

	return buf.Bytes(), nil
}

// Generate imports
func (g *GPUGoGenerator) generateImports() *ast.GenDecl {
	return &ast.GenDecl{
		Tok: token.IMPORT,
		Specs: []ast.Spec{
			&ast.ImportSpec{
				Name: ast.NewIdent("_"),
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"embed"`,
				},
			},
			&ast.ImportSpec{
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"unsafe"`,
				},
			},
		},
	}
}

// Generate GPU struct declaration
func (g *GPUGoGenerator) generateGPUStruct(gpuStruct *guixast.GPUStructDecl) *ast.GenDecl {
	fields := make([]*ast.Field, 0, len(gpuStruct.Struct.Fields))

	for _, field := range gpuStruct.Struct.Fields {
		goType, err := MapGPUTypeToGo(field.Type)
		if err != nil {
			// Fall back to field type name if mapping fails
			goType = field.Type.Name
		}

		astType := g.parseTypeString(goType)

		fields = append(fields, &ast.Field{
			Names: []*ast.Ident{ast.NewIdent(Title(field.Name))},
			Type:  astType,
		})
	}

	return &ast.GenDecl{
		Tok: token.TYPE,
		Specs: []ast.Spec{
			&ast.TypeSpec{
				Name: ast.NewIdent(gpuStruct.Name),
				Type: &ast.StructType{
					Fields: &ast.FieldList{
						List: fields,
					},
				},
			},
		},
	}
}

// Generate helper methods for GPU structs
func (g *GPUGoGenerator) generateHelperMethods(gpuStruct *guixast.GPUStructDecl) []ast.Decl {
	var decls []ast.Decl

	// Generate ToBytes method
	toBytesMethod := g.generateToBytesMethod(gpuStruct.Name)
	decls = append(decls, toBytesMethod)

	// Generate size validation init function
	sizeCheckInit := g.generateSizeCheckInit(gpuStruct)
	if sizeCheckInit != nil {
		decls = append(decls, sizeCheckInit)
	}

	return decls
}

// Generate ToBytes method
//
//	Generates: func (s *StructName) ToBytes() []byte {
//	    return unsafe.Slice((*byte)(unsafe.Pointer(s)), int(unsafe.Sizeof(*s)))
//	}
func (g *GPUGoGenerator) generateToBytesMethod(structName string) *ast.FuncDecl {
	return &ast.FuncDecl{
		Recv: &ast.FieldList{
			List: []*ast.Field{
				{
					Names: []*ast.Ident{ast.NewIdent("s")},
					Type:  &ast.StarExpr{X: ast.NewIdent(structName)},
				},
			},
		},
		Name: ast.NewIdent("ToBytes"),
		Type: &ast.FuncType{
			Results: &ast.FieldList{
				List: []*ast.Field{
					{
						Type: &ast.ArrayType{
							Elt: ast.NewIdent("byte"),
						},
					},
				},
			},
		},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.ReturnStmt{
					Results: []ast.Expr{
						// unsafe.Slice((*byte)(unsafe.Pointer(s)), int(unsafe.Sizeof(*s)))
						&ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("unsafe"),
								Sel: ast.NewIdent("Slice"),
							},
							Args: []ast.Expr{
								// (*byte)(unsafe.Pointer(s))
								&ast.CallExpr{
									Fun: &ast.ParenExpr{
										X: &ast.StarExpr{
											X: ast.NewIdent("byte"),
										},
									},
									Args: []ast.Expr{
										&ast.CallExpr{
											Fun: &ast.SelectorExpr{
												X:   ast.NewIdent("unsafe"),
												Sel: ast.NewIdent("Pointer"),
											},
											Args: []ast.Expr{ast.NewIdent("s")},
										},
									},
								},
								// int(unsafe.Sizeof(*s))
								&ast.CallExpr{
									Fun: ast.NewIdent("int"),
									Args: []ast.Expr{
										&ast.CallExpr{
											Fun: &ast.SelectorExpr{
												X:   ast.NewIdent("unsafe"),
												Sel: ast.NewIdent("Sizeof"),
											},
											Args: []ast.Expr{
												&ast.StarExpr{
													X: ast.NewIdent("s"),
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

// Generate size check init function
func (g *GPUGoGenerator) generateSizeCheckInit(gpuStruct *guixast.GPUStructDecl) *ast.FuncDecl {
	// Calculate expected size
	expectedSize, _, err := CalculateStructSize(gpuStruct.Struct.Fields)
	if err != nil {
		// Can't validate size for this struct
		return nil
	}

	return &ast.FuncDecl{
		Name: ast.NewIdent("init"),
		Type: &ast.FuncType{},
		Body: &ast.BlockStmt{
			List: []ast.Stmt{
				&ast.AssignStmt{
					Lhs: []ast.Expr{ast.NewIdent("expectedSize")},
					Tok: token.DEFINE,
					Rhs: []ast.Expr{
						&ast.CallExpr{
							Fun: ast.NewIdent("uintptr"),
							Args: []ast.Expr{
								&ast.BasicLit{
									Kind:  token.INT,
									Value: fmt.Sprintf("%d", expectedSize),
								},
							},
						},
					},
				},
				&ast.IfStmt{
					Cond: &ast.BinaryExpr{
						X: &ast.CallExpr{
							Fun: &ast.SelectorExpr{
								X:   ast.NewIdent("unsafe"),
								Sel: ast.NewIdent("Sizeof"),
							},
							Args: []ast.Expr{
								&ast.CompositeLit{
									Type: ast.NewIdent(gpuStruct.Name),
								},
							},
						},
						Op: token.NEQ,
						Y:  ast.NewIdent("expectedSize"),
					},
					Body: &ast.BlockStmt{
						List: []ast.Stmt{
							&ast.ExprStmt{
								X: &ast.CallExpr{
									Fun: ast.NewIdent("panic"),
									Args: []ast.Expr{
										&ast.BasicLit{
											Kind:  token.STRING,
											Value: fmt.Sprintf(`"%s size mismatch with WGSL"`, gpuStruct.Name),
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

// Generate shader embed declarations
func (g *GPUGoGenerator) generateShaderEmbed() []ast.Decl {
	// Create a unique variable name based on the shader filename
	// e.g., "candlestick_types.wgsl" -> "CandlestickTypesShaderSource"
	baseName := strings.TrimSuffix(g.shaderFilename, ".wgsl")
	parts := strings.Split(baseName, "_")
	for i, part := range parts {
		parts[i] = Title(part)
	}
	varName := strings.Join(parts, "") + "ShaderSource"

	return []ast.Decl{
		// Comment directive
		&ast.GenDecl{
			Tok: token.VAR,
			Doc: &ast.CommentGroup{
				List: []*ast.Comment{
					{Text: fmt.Sprintf("//go:embed %s", g.shaderFilename)},
				},
			},
			Specs: []ast.Spec{
				&ast.ValueSpec{
					Names: []*ast.Ident{ast.NewIdent(varName)},
					Type:  ast.NewIdent("string"),
				},
			},
		},
	}
}

// Parse a type string into an AST type expression
func (g *GPUGoGenerator) parseTypeString(typeStr string) ast.Expr {
	// Handle pointer types
	if strings.HasPrefix(typeStr, "*") {
		return &ast.StarExpr{
			X: g.parseTypeString(typeStr[1:]),
		}
	}

	// Handle slice types
	if strings.HasPrefix(typeStr, "[]") {
		return &ast.ArrayType{
			Elt: g.parseTypeString(typeStr[2:]),
		}
	}

	// Handle array types [N]T
	if strings.HasPrefix(typeStr, "[") {
		closeBracket := strings.Index(typeStr, "]")
		if closeBracket > 0 {
			sizeStr := typeStr[1:closeBracket]
			elemType := typeStr[closeBracket+1:]

			return &ast.ArrayType{
				Len: &ast.BasicLit{
					Kind:  token.INT,
					Value: sizeStr,
				},
				Elt: g.parseTypeString(elemType),
			}
		}
	}

	// Simple identifier
	return ast.NewIdent(typeStr)
}

// Title converts first letter to uppercase (simple version)
func Title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
