//go:build js && wasm
// +build js,wasm

// Code generated by guix. DO NOT EDIT.

package main

import (
	"github.com/gaarutyunov/guix/pkg/runtime"
	"syscall/js"
)

type App struct {
	app                 *runtime.App
	counterChan         chan int
	autoCardInstance    *AutoCard
	liveCounterInstance *LiveCounter
}

func NewApp() *App {
	c := &App{}
	c.counterChan = make(chan int, 10)
	c.autoCardInstance = NewAutoCard(WithTitle("Auto-generated"), WithSubtitle("Using @props directive"), WithHighlighted(true))
	c.liveCounterInstance = NewLiveCounter(WithCount(c.counterChan))
	return c
}
func (c *App) BindApp(app *runtime.App) {
	c.app = app
	if c.autoCardInstance != nil {
		c.autoCardInstance.BindApp(app)
	}
	if c.liveCounterInstance != nil {
		c.liveCounterInstance.BindApp(app)
	}
}
func (c *App) Render() *runtime.VNode {
	return func() *runtime.VNode {
		return runtime.Div(runtime.Class("app-container"), runtime.H1(runtime.Text("Parameter Passing Examples")), runtime.Div(runtime.Class("section"), runtime.H2(runtime.Text("Auto Props (@props directive)")), runtime.P(runtime.Text("Component defined: @props func AutoCard(title string, subtitle string, highlighted bool)")), runtime.P(runtime.Text("Usage: NewAutoCard(WithTitle(\"...\"), WithSubtitle(\"...\"), WithHighlighted(true))")), c.autoCardInstance.Render()), runtime.Div(runtime.Class("section"), runtime.H2(runtime.Text("Channel with @props")), runtime.P(runtime.Text("Component defined: @props func LiveCounter(count chan int)")), runtime.P(runtime.Text("Usage: NewLiveCounter(WithCount(channel))")), c.liveCounterInstance.Render()), runtime.Div(runtime.Class("info-section"), runtime.H2(runtime.Text("Other Parameter Passing Styles")), runtime.P(runtime.Text("See the README.md for examples of:")), runtime.Div(runtime.P(runtime.Text("• Normal Parameters: NewSimpleCard(title, description)")), runtime.P(runtime.Text("• Props Struct: NewUserProfile(UserProfileProps{...})")), runtime.P(runtime.Text("• Multiple Parameters: NewProductCard(name, price, inStock)")), runtime.P(runtime.Text("• Variadic Parameters: NewMessageList(msg1, msg2, msg3, ...)")))))
	}()
}
func (c *App) Mount(parent js.Value) {
	runtime.Mount(c.Render(), parent)
}
func (c *App) Unmount() {
}
func (c *App) Update() {
	if c.app != nil {
		c.app.Update()
	}
}
